import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, YAxis } from "recharts";
import { Apple, Calculator, ChevronDown, CloudOff, Heart, Languages, Leaf, Moon, PackageOpen, RefreshCw, Search, Settings, ShoppingBasket, Sun, TrendingDown, TrendingUp, Wifi } from "lucide-react";
import { CACHE_KEYS, MARKET_ENDPOINTS, REFRESH_INTERVAL_MS } from "@/lib/market-config";
import { mockHistory, mockPrices, validHistory, validPrices, type HistoryResponse, type PriceItem, type PricesResponse } from "@/lib/market-data";

type Language = "ar" | "en";
type Theme = "light" | "dark";
type View = "market" | "watchlist" | "calculator" | "settings";
type Source = "live" | "cache" | "mock";

const copy = {
  ar: { app:"سوقي", subtitle:"أسعار السوق اليوم", market:"السوق", watchlist:"المفضلة", calculator:"الحاسبة", settings:"الإعدادات", search:"ابحث عن منتج أو سوق", all:"الكل", vegetables:"خضر", fruits:"فواكه", perKg:"لكل كغ", updated:"آخر تحديث", refreshing:"جاري تحديث الأسعار…", live:"مباشر", offline:"غير متصل — نعرض آخر البيانات المتاحة", mock:"بيانات تجريبية — المصدر غير متاح", empty:"لا توجد نتائج", emptySub:"جرّب البحث بكلمة أخرى أو غيّر التصنيف.", watchEmpty:"قائمة المفضلة فارغة", watchSub:"اضغط على القلب بجانب أي منتج لمتابعته هنا.", calcTitle:"حاسبة المشتريات", product:"المنتج", quantity:"الكمية (كغ)", total:"المجموع التقديري", language:"اللغة", theme:"المظهر", arabic:"العربية", english:"English", light:"فاتح", dark:"داكن", data:"البيانات", auto:"تتجدد تلقائياً كل 5 دقائق", pull:"اسحب للأسفل للتحديث", retry:"إعادة المحاولة", source:"مصدر الأسعار", history:"تاريخ السعر — 90 يوماً", today:"اليوم" },
  en: { app:"Souqi", subtitle:"Today’s market prices", market:"Market", watchlist:"Watchlist", calculator:"Calculator", settings:"Settings", search:"Search product or market", all:"All", vegetables:"Vegetables", fruits:"Fruits", perKg:"per kg", updated:"Last updated", refreshing:"Refreshing prices…", live:"Live", offline:"Offline — showing the latest available data", mock:"Demo data — source unavailable", empty:"No results found", emptySub:"Try another search or change the category.", watchEmpty:"Your watchlist is empty", watchSub:"Tap the heart beside any product to follow it here.", calcTitle:"Shopping calculator", product:"Product", quantity:"Quantity (kg)", total:"Estimated total", language:"Language", theme:"Appearance", arabic:"العربية", english:"English", light:"Light", dark:"Dark", data:"Data", auto:"Refreshes automatically every 5 minutes", pull:"Pull down to refresh", retry:"Try again", source:"Price source", history:"Price history — 90 days", today:"Today" },
};

const names: Record<string, [string,string]> = { potato:["بطاطا","Potato"], tomato:["طماطم","Tomato"], onion:["بصل","Onion"], carrot:["جزر","Carrot"], zucchini:["كوسة","Zucchini"], pepper:["فلفل","Pepper"], orange:["برتقال","Orange"], apple:["تفاح","Apple"], banana:["موز","Banana"], date:["تمر","Dates"], lemon:["ليمون","Lemon"], strawberry:["فراولة","Strawberry"] };
const markets: Record<string,string> = { Boufarik:"بوفاريك", "Boumerdès":"بومرداس", "El Harrach":"الحراش", Blida:"البليدة", Algiers:"الجزائر", "Médéa":"المدية", Biskra:"بسكرة", Tipaza:"تيبازة" };

function readStorage<T>(key:string, fallback:T):T { try { const v=localStorage.getItem(key); return v ? JSON.parse(v) as T : fallback; } catch { return fallback; } }
function writeStorage(key:string, value:unknown) { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* storage may be unavailable */ } }
function marketLabel(market:string, ar:boolean){ const label=markets[market]??markets[market.toLowerCase()]; return ar?(label??market):label??market.charAt(0).toUpperCase()+market.slice(1); }

export function MarketApp() {
  const [language,setLanguage]=useState<Language>("ar"); const [theme,setTheme]=useState<Theme>("light"); const [view,setView]=useState<View>("market");
  const [prices,setPrices]=useState<PricesResponse>(mockPrices); const [history,setHistory]=useState<HistoryResponse>(mockHistory); const [source,setSource]=useState<Source>("mock");
  const [refreshing,setRefreshing]=useState(false); const [online,setOnline]=useState(true); const [query,setQuery]=useState(""); const [category,setCategory]=useState("all");
  const [favorites,setFavorites]=useState<string[]>([]); const [selected,setSelected]=useState("potato@Boufarik"); const [quantity,setQuantity]=useState(2); const [pull,setPull]=useState(0);
  const startY=useRef<number|null>(null); const t=copy[language]; const isAr=language==="ar";

  const refresh=useCallback(async()=>{ setRefreshing(true); try { const [p,h]=await Promise.all([fetch(MARKET_ENDPOINTS.prices,{cache:"no-store"}),fetch(MARKET_ENDPOINTS.history,{cache:"no-store"})]); if(!p.ok||!h.ok) throw new Error("feed unavailable"); const pj:unknown=await p.json(), hj:unknown=await h.json(); if(!validPrices(pj)||!validHistory(hj)) throw new Error("invalid feed"); setPrices(pj);setHistory(hj);setSource("live");writeStorage(CACHE_KEYS.prices,pj);writeStorage(CACHE_KEYS.history,hj); } catch { const cp=readStorage<PricesResponse|null>(CACHE_KEYS.prices,null), ch=readStorage<HistoryResponse|null>(CACHE_KEYS.history,null); if(cp&&ch&&validPrices(cp)&&validHistory(ch)){setPrices(cp);setHistory(ch);setSource("cache");} else {setPrices(mockPrices);setHistory(mockHistory);setSource("mock");} } finally {setRefreshing(false);} },[]);

  useEffect(()=>{ setLanguage(readStorage(CACHE_KEYS.language,"ar"));setTheme(readStorage(CACHE_KEYS.theme,"light"));setFavorites(readStorage(CACHE_KEYS.watchlist,[]));setOnline(navigator.onLine); void refresh(); const timer=window.setInterval(()=>void refresh(),REFRESH_INTERVAL_MS); const onOnline=()=>{setOnline(true);void refresh()}; const onOffline=()=>setOnline(false);window.addEventListener("online",onOnline);window.addEventListener("offline",onOffline);if("serviceWorker" in navigator) void navigator.serviceWorker.register("/sw.js");return()=>{clearInterval(timer);window.removeEventListener("online",onOnline);window.removeEventListener("offline",onOffline)}},[refresh]);
  useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=isAr?"rtl":"ltr";document.documentElement.classList.toggle("dark",theme==="dark");writeStorage(CACHE_KEYS.language,language);writeStorage(CACHE_KEYS.theme,theme)},[language,theme,isAr]);

  const entries=useMemo(()=>Object.entries(prices.prices),[prices]);
  const visible=entries.filter(([key,item])=>{const term=query.trim().toLowerCase();const label=names[item.product]?.[isAr?0:1]??item.product;const market=marketLabel(item.market,isAr).toLowerCase();return(category==="all"||item.category===category)&&(!term||label.toLowerCase().includes(term)||market.includes(term))&&(view!=="watchlist"||favorites.includes(key))});
  const toggleFavorite=(key:string)=>setFavorites(prev=>{const next=prev.includes(key)?prev.filter(x=>x!==key):[...prev,key];writeStorage(CACHE_KEYS.watchlist,next);return next});
  const money=(n:number)=>`${new Intl.NumberFormat(isAr?"ar-DZ":"en-DZ",{maximumFractionDigits:0}).format(n)} ${isAr?"دج":"DZD"}`;
  const dateLabel=new Intl.DateTimeFormat(isAr?"ar-DZ":"en-DZ",{hour:"2-digit",minute:"2-digit",day:"numeric",month:"short"}).format(new Date(prices.generated_at));
  const selectedItem=prices.prices[selected]??entries[0]?.[1];
  const gesture={onTouchStart:(e:React.TouchEvent)=>{if(window.scrollY===0)startY.current=e.touches[0]?.clientY??null},onTouchMove:(e:React.TouchEvent)=>{if(startY.current!==null)setPull(Math.min(84,Math.max(0,(e.touches[0]?.clientY??0)-startY.current)))},onTouchEnd:()=>{if(pull>62)void refresh();setPull(0);startY.current=null}};

  return <div {...gesture} className="min-h-screen bg-background text-foreground transition-colors duration-300">
    <div className="pointer-events-none fixed inset-x-0 top-0 z-50 flex justify-center transition-transform" style={{transform:`translateY(${Math.max(-52,pull-52)}px)`}}><div className="mt-2 flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-xs font-bold text-primary-foreground shadow-lg"><RefreshCw size={14} className={pull>62?"animate-spin":""}/>{t.pull}</div></div>
    <header className="sticky top-0 z-30 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-blue"><ShoppingBasket size={22}/></span><div><h1 className="font-display text-xl font-extrabold">{t.app}</h1><p className="text-xs text-muted-foreground">{t.subtitle}</p></div></div><button aria-label={t.theme} onClick={()=>setTheme(x=>x==="light"?"dark":"light")} className="icon-button">{theme==="light"?<Moon size={19}/>:<Sun size={19}/>}</button></div></header>
    <main className="mx-auto max-w-5xl px-4 pb-28 pt-5 md:px-6">
      <div className={`mb-5 flex items-center justify-between gap-3 rounded-xl border px-4 py-3 text-sm ${source==="live"&&online?"border-info/25 bg-info-soft text-info":"border-warning/25 bg-warning-soft text-warning"}`}><div className="flex items-center gap-2">{source==="live"&&online?<Wifi size={17}/>:<CloudOff size={17}/>}<span>{source==="live"&&online?t.live:source==="cache"?t.offline:t.mock}</span></div><button aria-label={t.retry} onClick={()=>void refresh()} className="icon-button-sm"><RefreshCw size={15} className={refreshing?"animate-spin":""}/></button></div>
      {(view==="market"||view==="watchlist")&&<><div className="mb-5 flex items-end justify-between"><div><p className="text-sm text-muted-foreground">{t.updated}</p><p className="mt-1 font-display text-2xl font-bold">{dateLabel}</p></div><div className="rounded-full bg-accent px-3 py-1.5 text-xs font-bold text-accent-foreground">{entries.length} {isAr?"منتج":"items"}</div></div>
      <div className="relative mb-4"><Search className="absolute start-4 top-1/2 -translate-y-1/2 text-muted-foreground" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} className="h-12 w-full rounded-xl border border-border bg-card ps-12 pe-4 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-ring/15"/></div>
      <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{([['all',t.all],['vegetable',t.vegetables],['fruit',t.fruits]] as Array<[string,string]>).map(([v,l])=><button key={v} onClick={()=>setCategory(v)} className={category===v?"filter-active":"filter-button"}>{l}</button>)}</div>
      {refreshing?<Skeletons/>:visible.length?<div className="grid gap-3 md:grid-cols-2">{visible.map(([key,item])=><PriceCard key={key} itemKey={key} item={item} language={language} favorite={favorites.includes(key)} onFavorite={()=>toggleFavorite(key)} onSelect={()=>setSelected(key)} money={money} history={history[key]??[]}/>)}</div>:<Empty title={view==="watchlist"?t.watchEmpty:t.empty} detail={view==="watchlist"?t.watchSub:t.emptySub}/>}</>}
      {view==="calculator"&&<section><SectionTitle icon={<Calculator/>} title={t.calcTitle}/><div className="rounded-2xl border border-border bg-card p-5 shadow-card"><label className="label">{t.product}</label><div className="relative mb-5"><select value={selected} onChange={e=>setSelected(e.target.value)} className="field appearance-none">{entries.map(([key,item])=><option key={key} value={key}>{names[item.product]?.[isAr?0:1]??item.product} — {marketLabel(item.market,isAr)}</option>)}</select><ChevronDown className="pointer-events-none absolute end-4 top-1/2 -translate-y-1/2 text-muted-foreground" size={18}/></div><label className="label">{t.quantity}</label><input className="field mb-6" type="number" min="0.1" step="0.1" value={quantity} onChange={e=>setQuantity(Math.max(0,Number(e.target.value)))}/><div className="rounded-xl bg-primary p-5 text-primary-foreground"><p className="text-sm opacity-80">{t.total}</p><p className="mt-2 font-display text-4xl font-extrabold" dir="ltr">{money((selectedItem?.price??0)*quantity)}</p><p className="mt-2 text-xs opacity-75">{quantity} kg × {money(selectedItem?.price??0)}</p></div></div></section>}
      {view==="settings"&&<section><SectionTitle icon={<Settings/>} title={t.settings}/><div className="space-y-4"><SettingCard icon={<Languages/>} title={t.language}><div className="segmented"><button onClick={()=>setLanguage("ar")} className={language==="ar"?"selected":""}>{t.arabic}</button><button onClick={()=>setLanguage("en")} className={language==="en"?"selected":""}>{t.english}</button></div></SettingCard><SettingCard icon={theme==="light"?<Sun/>:<Moon/>} title={t.theme}><div className="segmented"><button onClick={()=>setTheme("light")} className={theme==="light"?"selected":""}>{t.light}</button><button onClick={()=>setTheme("dark")} className={theme==="dark"?"selected":""}>{t.dark}</button></div></SettingCard><SettingCard icon={<RefreshCw/>} title={t.data}><p className="text-sm text-muted-foreground">{t.auto}</p><p className="mt-1 break-all text-xs text-muted-foreground/70">{t.source}: GitHub Raw</p></SettingCard></div></section>}
    </main>
    <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-card/95 pb-[env(safe-area-inset-bottom)] backdrop-blur-xl"><div className="mx-auto grid max-w-lg grid-cols-4 px-2 py-2">{([{id:"market",icon:ShoppingBasket,label:t.market},{id:"watchlist",icon:Heart,label:t.watchlist},{id:"calculator",icon:Calculator,label:t.calculator},{id:"settings",icon:Settings,label:t.settings}] as const).map(n=><button key={n.id} onClick={()=>setView(n.id)} className={view===n.id?"nav-active":"nav-button"}><n.icon size={21} fill={view===n.id&&n.id==="watchlist"?"currentColor":"none"}/><span>{n.label}</span></button>)}</div></nav>
  </div>
}

function PriceCard({itemKey,item,language,favorite,onFavorite,onSelect,money,history}:{itemKey:string;item:PriceItem;language:Language;favorite:boolean;onFavorite:()=>void;onSelect:()=>void;money:(n:number)=>string;history:Array<{date:string;price:number}>}){const ar=language==="ar", up=item.change>0, down=item.change<0;return <article onClick={onSelect} className="group rounded-2xl border border-border bg-card p-4 shadow-card transition duration-200 hover:-translate-y-0.5 hover:shadow-card-hover"><div className="flex items-start gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-secondary text-primary">{item.category==="fruit"?<Apple size={22}/>:<Leaf size={22}/>}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="font-display text-base font-bold">{names[item.product]?.[ar?0:1]??item.product}</h3><p className="mt-0.5 text-xs text-muted-foreground">{ar?(markets[item.market]??item.market):item.market}</p></div><button aria-label="favorite" onClick={e=>{e.stopPropagation();onFavorite()}} className="icon-button-sm"><Heart size={18} className={favorite?"fill-primary text-primary":""}/></button></div><div className="mt-4 flex items-end justify-between"><div><p className="font-display text-2xl font-extrabold" dir="ltr">{money(item.price)}</p><p className="text-[11px] text-muted-foreground">{ar?"لكل كغ":"per kg"}</p></div><div className={`flex items-center gap-1 text-xs font-bold ${up?"text-rise":down?"text-fall":"text-muted-foreground"}`}>{up?<TrendingUp size={15}/>:down?<TrendingDown size={15}/>:null}<span dir="ltr">{item.change>0?"+":""}{item.change}%</span></div></div></div></div><div className="mt-3 h-10"><ResponsiveContainer width="100%" height="100%"><AreaChart data={history.slice(-30)}><defs><linearGradient id={`g-${item.product}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--primary)" stopOpacity={0.25}/><stop offset="1" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><YAxis hide domain={["dataMin - 5","dataMax + 5"]}/><Tooltip content={()=>null}/><Area type="monotone" dataKey="price" stroke="var(--primary)" strokeWidth={2} fill={`url(#g-${item.product})`} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></article>}
function Skeletons(){return <div className="grid gap-3 md:grid-cols-2">{Array.from({length:6}).map((_,i)=><div key={i} className="h-44 animate-pulse rounded-2xl border border-border bg-card p-4"><div className="h-full rounded-xl bg-muted"/></div>)}</div>}
function Empty({title,detail}:{title:string;detail:string}){return <div className="py-16 text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-secondary text-primary"><PackageOpen size={28}/></span><h2 className="mt-4 font-display text-lg font-bold">{title}</h2><p className="mx-auto mt-2 max-w-xs text-sm leading-6 text-muted-foreground">{detail}</p></div>}
function SectionTitle({icon,title}:{icon:React.ReactNode;title:string}){return <div className="mb-5 flex items-center gap-3 text-primary">{icon}<h2 className="font-display text-2xl font-extrabold text-foreground">{title}</h2></div>}
function SettingCard({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-border bg-card p-5 shadow-card"><div className="mb-4 flex items-center gap-3 text-primary">{icon}<h3 className="font-display font-bold text-foreground">{title}</h3></div>{children}</div>}
